# OVERALL FINDINGS:

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Specify file locations for data files

schools = "Instructions/PyCitySchools/Resources/schools_complete.csv"
students = "Instructions/PyCitySchools/Resources/students_complete.csv"

In [3]:

# Read CSV Files

schools_df = pd.read_csv(schools)
students_df = pd.read_csv(students)
students_df.head()
schools_df

    School ID            school_name      type  size   budget
0           0      Huang High School  District  2917  1910635
1           1   Figueroa High School  District  2949  1884411
2           2    Shelton High School   Charter  1761  1056600
3           3  Hernandez High School  District  4635  3022020
4           4    Griffin High School   Charter  1468   917500
5           5     Wilson High School   Charter  2283  1319574
6           6    Cabrera High School   Charter  1858  1081356
7           7     Bailey High School  District  4976  3124928
8           8     Holden High School   Charter   427   248087
9           9       Pena High School   Charter   962   585858
10         10     Wright High School   Charter  1800  1049400
11         11  Rodriguez High School  District  3999  2547363
12         12    Johnson High School  District  4761  3094650
13         13       Ford High School  District  2739  1763916
14         14     Thomas High School   Charter  1635  1043130

In [4]:
students_df

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84
5,5,Bryan Miranda,M,9th,Huang High School,94,94
6,6,Sheena Carter,F,11th,Huang High School,82,80
7,7,Nicole Baker,F,12th,Huang High School,96,69
8,8,Michael Roth,M,10th,Huang High School,95,87
9,9,Matthew Greene,M,10th,Huang High School,96,84
10,10,Andrew Alexander,M,10th,Huang High School,90,70
11,11,Daniel Cooper,M,10th,Huang High School,78,77
12,12,Brittney Walker,F,9th,Huang High School,64,79
13,13,William Long,M,9th,Huang High School,71,79
14,14,Tammy Hebert,F,10th,Huang High School,85,67
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88
16,16,Donald Zamora,M,9th,Huang High School,88,55
17,17,Kimberly Santiago,F,9th,Huang High School,74,75
18,18,Kevin Stevens,M,9th,Huang High School,64,69
19,19,Brandi Lyons,F,9th,Huang High School,89,80
20,20,Lisa Davis,F,10th,Huang High School,91,89
21,21,Kristen Lopez,F,10th,Huang High School,90,77
22,22,Kimberly Stewart,F,11th,Huang High School,99,84
23,23,Christopher Parker,M,9th,Huang High School,81,68
24,24,Chelsea Griffith,F,11th,Huang High School,85,73
25,25,Cesar Morris,M,9th,Huang High School,92,70
26,26,Melanie Decker,F,9th,Huang High School,63,85
27,27,Tracey Oconnor,F,10th,Huang High School,80,58
28,28,Kelly James,F,11th,Huang High School,73,55
29,29,Nicole Brown,F,12th,Huang High School,90,88
...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73
39152,39152,Lori Moore,F,9th,Thomas High School,98,84
39153,39153,William Hubbard,M,9th,Thomas High School,80,75
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71
39155,39155,John Brooks,M,10th,Thomas High School,92,98
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86
39161,39161,April Reyes,F,10th,Thomas High School,70,84
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77
39163,39163,John Reese,M,11th,Thomas High School,90,75
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76
39165,39165,Donna Howard,F,12th,Thomas High School,99,90
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75

In [5]:
# Merge into one data frame:

merged = pd.merge(schools_df, students_df, on="school_name")
merged

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
6,0,Huang High School,District,2917,1910635,6,Sheena Carter,F,11th,82,80
7,0,Huang High School,District,2917,1910635,7,Nicole Baker,F,12th,96,69
8,0,Huang High School,District,2917,1910635,8,Michael Roth,M,10th,95,87
9,0,Huang High School,District,2917,1910635,9,Matthew Greene,M,10th,96,84
10,0,Huang High School,District,2917,1910635,10,Andrew Alexander,M,10th,90,70
11,0,Huang High School,District,2917,1910635,11,Daniel Cooper,M,10th,78,77
12,0,Huang High School,District,2917,1910635,12,Brittney Walker,F,9th,64,79
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
14,0,Huang High School,District,2917,1910635,14,Tammy Hebert,F,10th,85,67
15,0,Huang High School,District,2917,1910635,15,Dr. Jordan Carson,M,11th,94,88
16,0,Huang High School,District,2917,1910635,16,Donald Zamora,M,9th,88,55
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
18,0,Huang High School,District,2917,1910635,18,Kevin Stevens,M,9th,64,69
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
20,0,Huang High School,District,2917,1910635,20,Lisa Davis,F,10th,91,89
21,0,Huang High School,District,2917,1910635,21,Kristen Lopez,F,10th,90,77
22,0,Huang High School,District,2917,1910635,22,Kimberly Stewart,F,11th,99,84
23,0,Huang High School,District,2917,1910635,23,Christopher Parker,M,9th,81,68
24,0,Huang High School,District,2917,1910635,24,Chelsea Griffith,F,11th,85,73
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
26,0,Huang High School,District,2917,1910635,26,Melanie Decker,F,9th,63,85
27,0,Huang High School,District,2917,1910635,27,Tracey Oconnor,F,10th,80,58
28,0,Huang High School,District,2917,1910635,28,Kelly James,F,11th,73,55
29,0,Huang High School,District,2917,1910635,29,Nicole Brown,F,12th,90,88
...,...,...,...,...,...,...,...,...,...,...,...
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39141,14,Thomas High School,Charter,1635,1043130,39141,Jonathan Sullivan,M,10th,86,93
39142,14,Thomas High School,Charter,1635,1043130,39142,Deborah Higgins DDS,F,10th,96,83
39143,14,Thomas High School,Charter,1635,1043130,39143,Steven Jackson,M,11th,71,93
39144,14,Thomas High School,Charter,1635,1043130,39144,Cristian Webster,M,12th,77,87
39145,14,Thomas High School,Charter,1635,1043130,39145,Audrey Fry,F,10th,94,74
39146,14,Thomas High School,Charter,1635,1043130,39146,Michael Carroll,M,9th,69,95
39147,14,Thomas High School,Charter,1635,1043130,39147,Raymond Hawkins,M,10th,88,81
39148,14,Thomas High School,Charter,1635,1043130,39148,Christopher Wilson,M,10th,89,89
39149,14,Thomas High School,Charter,1635,1043130,39149,Glenda Fletcher,F,11th,82,93
39150,14,Thomas High School,Charter,1635,1043130,39150,Jennifer Hamilton,F,11th,80,75
39151,14,Thomas High School,Charter,1635,1043130,39151,Shannon Williams,F,10th,84,73
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39154,14,Thomas High School,Charter,1635,1043130,39154,Bradley Johnson,M,12th,91,71
39155,14,Thomas High School,Charter,1635,1043130,39155,John Brooks,M,10th,92,98
39156,14,Thomas High School,Charter,1635,1043130,39156,Stephanie Contreras,F,11th,79,95
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39158,14,Thomas High School,Charter,1635,1043130,39158,Kari Holloway,F,10th,87,90
39159,14,Thomas High School,Charter,1635,1043130,39159,Kimberly Cabrera,F,11th,85,72
39160,14,Thomas High School,Charter,1635,1043130,39160,Katie Weaver,F,11th,89,86
39161,14,Thomas High School,Charter,1635,1043130,39161,April Reyes,F,10th,70,84
39162,14,Thomas High School,Charter,1635,1043130,39162,Derek Weeks,M,12th,94,77
39163,14,Thomas High School,Charter,1635,1043130,39163,John Reese,M,11th,90,75
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39165,14,Thomas High School,Charter,1635,1043130,39165,Donna Howard,F,12th,99,90
39166,14,Thomas High School,Charter,1635,1043130,39166,Dawn Bell,F,10th,95,70
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84
39168,14,Thomas High School,Charter,1635,1043130,39168,Desiree Kidd,F,10th,99,90
39169,14,Thomas High School,Charter,1635,1043130,39169,Carolyn Jackson,F,11th,95,75

In [6]:
#count nuymber of schools
total_schools = schools_df["School ID"].count()
total_schools

15

In [7]:
#count number of students
total_students = students_df["Student ID"].count()
total_students

39170

In [8]:
#Total Budget
total_budget = schools_df["budget"].sum()
total_budget

#Per student Budget
per_student_budget = total_budget/total_students

total_budget

24649428

In [9]:
per_student_budget

629.2935409752362

In [10]:
#Average Reading
average_reading = students_df['reading_score'].mean()
average_reading

81.87784018381414

In [11]:
#Average Math
average_math = students_df['math_score'].mean()
average_math

78.98537145774827

In [12]:
# % Passing Math
pass_math = (students_df['math_score']>=70).sum()/total_students
pass_math*100

74.9808526933878

In [13]:
# % Passing Reading
pass_reading = (students_df['reading_score']>=70).sum()/total_students
pass_reading*100

85.80546336482001

In [14]:
# Overall Passing Rate (Average of the above two)
pass_overall = (pass_math+pass_reading)/2
pass_overall*100

80.3931580291039

In [15]:
district_summary_df = pd.DataFrame({
    "Total Schools":[total_schools],
    "Total Budget":[total_budget],
    "Total Students":[total_students],
    "Avg Math Score":[average_math],
    "Avg Reading Score":[average_reading],
    "Percentage Passing Math":[pass_math],
    "Percentage Passing Reading":[pass_reading],
    "Percentage Passing Overall":[pass_overall]
})
district_summary_df

,Total Schools,Total Budget,Total Students,Avg Math Score,Avg Reading Score,Percentage Passing Math,Percentage Passing Reading,Percentage Passing Overall
0,15,24649428,39170,78.985371,81.87784,0.749809,0.858055,0.803932

In [21]:
school = schools_df["name"]
school_type = schools_df["type"]
students = schools_df["size"]
budget = schools_df["budget"]
math_average = merged.groupby(["school"])["math_score"].mean()
reading_average = merged.groupby(["school"])["reading_score"].mean()
math_passing = merged[students_df.math_score>=70].groupby('school')['math_score'].count()/merged.groupby(["school"])["Student ID"].count()
math_passing = math_passing *100
reading_passing = merged[students_df.reading_score>=70].groupby('school')['reading_score'].count()/merged.groupby(["school"])["Student ID"].count()
reading_passing = reading_passing*100
overall_passing = (math_passing + reading_passing)/2

# # school_overview1_df = pd.DataFrame({
# #     "School":school,
# #     "School Type":school_type,
# #     "Total Students":students,
# #     "Total Budget":total_budget,
# #     "Budget Per School":budget
# # })
# # school_overview2_df = pd.DataFrame({
# #     "Avg Math Score":math_average,
# #     "Avg Reading Score":reading_average,
# #     "Percentage Passing Math":math_passing,
# #     "Percentage Passing Reading":reading_passing,
# #     "Percentage Passing Overall":overall_passing
# })

# # school_overview = school_overview1_df.join(school_overview2_df,on='School',how='inner')
# # school_overview

KeyError: 'name'

In [18]:

top5_df = school_overview.sort_values("Percentage Passing Overall", ascending=False)
top5_df = top5_df.head()
top5_df

NameError: name 'school_overview' is not defined

In [ ]:

bottom5_df = school_overview.sort_values("Percentage Passing Overall", ascending=True)
bottom5_df = bottom5_df.head()
bottom5_df

In [22]:
ninth = merged[(merged["grade"] == "9th")]
tenth = merged[(merged["grade"] == "10th")]
eleventh = merged[(merged["grade"] == "11th")]
twelfth = merged[(merged["grade"] == "12th")]

ninthscore = ninth.groupby("school")["math_score"].mean()
tenthscore = tenth.groupby("school")["math_score"].mean()
eleventhscore = eleventh.groupby("school")["math_score"].mean()
twelfthscore = twelfth.groupby("school")["math_score"].mean()

mathscores=pd.DataFrame({
    "9th":ninthscore,
    "10th":tenthscore,
    "11th":eleventhscore,
    "12th":twelfthscore
})
mathscores

KeyError: 'school'

In [ ]:
ninereading = ninth.groupby("school")["reading_score"].mean()
tenreading = tenth.groupby("school")["reading_score"].mean()
elevenreading = eleventh.groupby("school")["reading_score"].mean()
twelvereading = twelfth.groupby("school")["reading_score"].mean()

readingscores=pd.DataFrame({
    "9th":ninereading,
    "10th":tenreading,
    "11th":elevenreading,
    "12th":twelvereading
})
readingscores

In [ ]:
budget_per_student = budget/students
bins = [0,585,615,645,675]
labels = ["<585","585-615","615-645","645-675"]
school_overview["Spending Ranges"] = pd.cut(budget_per_student,bins,labels=labels)

spendingmath = school_overview.groupby("Spending Ranges").mean()["Avg Math Score"]
spendingreading = school_overview.groupby("Spending Ranges").mean()["Avg Reading Score"]
spendingmathpass = school_overview.groupby("Spending Ranges").mean()["Percentage Passing Math"]
spendingreadpass = school_overview.groupby("Spending Ranges").mean()["Percentage Passing Reading"]
spendingoverallpass = (spendingmath+spendingreading)/2

spending_summary = pd.DataFrame({
    "Average Math Score":spendingmath,
    "Average Reading Score":spendingreading,
    "Passing Math":spendingmathpass,
    "Passing Reading":spendingreadpass,
    "Passing Overall":spendingoverallpass
})
spending_summary

In [ ]:

sizebins = [0,2000,4000,6000]
sizelabels = ["Small <2000","Medium 2000-4000","Large >4000"]
school_overview["Size Type"]=pd.cut(students,sizebins,labels=sizelabels)

sizemath = school_overview.groupby("Size Type").mean()["Avg Math Score"]
sizeread = school_overview.groupby("Size Type").mean()["Avg Reading Score"]
sizemathpass = school_overview.groupby("Size Type").mean()["Percentage Passing Math"]
sizereadpass = school_overview.groupby("Size Type").mean()["Percentage Passing Reading"]
sizeoverallpass = (sizemathpass+sizereadpass)/2

size_summary = pd.DataFrame({
    "Average Math Score":sizemath,
    "Average Reading Score":sizeread,
    "Passing Math":sizemathpass,
    "Passing Reading":sizereadpass,
    "Passing Overall":sizeoverallpass
})
size_summary

In [ ]:
athtype = school_overview.groupby("School Type")["Avg Math Score"].mean()
readingtype = school_overview.groupby("School Type")["Avg Reading Score"].mean()
passmathtype = school_overview.groupby("School Type")["Percentage Passing Math"].mean() 
passreadtype = school_overview.groupby("School Type")["Percentage Passing Reading"].mean()
passoveralltype = (passmath+passread)/2

type_df = pd.DataFrame({
    "Average Math Score":mathtype,
    "Average Reading Score":readingtype,
    "Passing Math":passmathtype,
    "Passing Reading":passreadtype,
    "Passing Overall":passoveralltype
})
type_df